name: Container
on: push

jobs:
  node-docker-container:
    runs-on: ubuntu-latest
    services:
      app:
        image: node:13.5.0-alpine3.10        
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: post a user
        run: "curl -X POST http://localhost:3001/api/user-H 'content-type: application/json' -d '{\"username\": \"hello\",\"address\": \"dwded\"}'"
      - name: Get users
        run: curl http://localhost:3001/api/users  
